### ISSUE TITLE
Changing different svm kernel type?

### ISSUE THREAD

**Issue by chengke96** [Mquinn960/offline-trainer#11]
Can i change the svm kernel type from linear and rbf to other kernel such as polynomial and sigmoid?
If yes, how?

**Comment by Mquinn960** [comment]
Hello @chengke96, changing the SVM kernel is as easy as changing the values in this file:

https://github.com/Mquinn960/offline-trainer/blob/master/src/com/mquinn/trainer/sl_extensions/SvmService.java

```    
protected SvmService(){

        svm = SVM.create();
        svm.setType(SVM.C_SVC);
        svm.setKernel(SVM.RBF);
        svm.setTermCriteria(new TermCriteria(TermCriteria.MAX_ITER, 100, 1e-6));
        logger = ResultLoggerService.getInstance(false);

    }
```

The available kernels in OpenCV are found here:

https://docs.opencv.org/3.4/d1/d2d/classcv_1_1ml_1_1SVM.html

You can also play about with any other model hyperparameters as you see fit.

Just remember when you're exporting the kernel, you'll need to do the same within the Sign Language App.

**Comment by chengke96** [comment]
@Mquinn960 Yes, edit by the method provided above successfully.
Can I confirm that in your case, the sample category matrix and simple confusion matrix are only appear in the result of svm kernel with linear. Even svm with rbf didn't come out the result of those matrix?

**Comment by Mquinn960** [comment]
Hey - if you didn't get an error, and you can't find the trained XML file, then that's odd.

This project used testing on both Linear and RBF kernels in the same manner.

@chengke96 can you try changing the file:

https://github.com/Mquinn960/offline-trainer/blob/master/src/com/mquinn/trainer/Main.java

```
        // SVM kernel types
        String[] kernels = new String[]{
            "rbf"
        };
```

Just remove the linear kernel entirely from the main method. The main method is there to test all the combinations of parameters/kernels.

**Comment by chengke96** [comment]
@Mquinn960 Successfully found both of linear and rbf trained XML files in offline-trainer file. 
Error below confusing me, does it affect anything?

![image](https://user-images.githubusercontent.com/55948336/87044650-6dcfbd00-c229-11ea-8755-8ca5a04efd4f.png)


Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) C:\build\3_4_winpack-bindings-win64-vc14-static\opencv\modules\core\src\pca.cpp:296: error: (-215:Assertion failed) !mean.empty() && !eigenvectors.empty() && ((mean.rows == 1 && mean.cols == data.cols) || (mean.cols == 1 && mean.rows == data.rows)) in function 'cv::PCA::project'
]

**Comment by Mquinn960** [comment]
Hey, same idea:

```
        // Methods of dimensionality reduction
        String[] dimReduceType = new String[]{
            "none"
        };
```

Try removing ```pca``` here - this is a type of dimensionality reduction which was used as an additional testing parameter. It uses Principal Component Analysis to "squash" the data.

It's possible the data is in a weird format for it, PCA can be quite hard particularly with malformed data.

**Comment by chengke96** [comment]
Nice! Thank you!

**Comment by chengke96** [comment]
![image](https://user-images.githubusercontent.com/55948336/87227752-a7dac380-c3cf-11ea-829a-b2ebf3cd0a35.png)

@Mquinn960 Hi, do you know why my class Q does not have any TP, but I still can detect the Q letter after the xml file imported to the app?

**Comment by Mquinn960** [comment]
@chengke96 good question! I'm actually not sure why this would be the case for "Q" in particular... Does this letter look OK in the output matrix?

**Comment by chengke96** [comment]
@Mquinn960 You mean after put the xml file into the sign app? The result is ok to detect the letter "Q" in phone

**Comment by Mquinn960** [comment]
Weird! Might be a logging issue or something.
