### ISSUE TITLE
Build Successful But no tests to run

### ISSUE THREAD

**Issue by Taqbeel** [Mquinn960/offline-trainer#12]
I have configured the maven as per documentation in description but when I run it build the project successfully but with no tests to run and no source to compile. 
when try to run java file from target folder with .. JAVA -jar outpufile.jar ... It says "no main manifest attribute in outputfile.jar".
How to make it run successfully and how to load dataset created with dataset-creator to get them trained,.

**Comment by Mquinn960** [comment]
Hello,

This is an academic project, it is offered as-is - there are currently no unit tests. If you want to write some and contribute a pull request, I'll have a look at it.

Please try loading the project that's in the repository, in IntelliJ IDEA if you are having issues with Maven. Use the run/build configuration from within the IDE, using the project settings that are already there.

If you want to purely use Maven, please debug this yourself, as I can't really offer any assistance. You need to use google to look for a solution to your issue, and explain what you've tried, and why it isn't working.

Kind regards,

Matt
