### ISSUE TITLE
No Testing

### ISSUE THREAD

**Issue by Miki3553** [Mquinn960/offline-trainer#14]
Hi, i got this issue:
mar 24, 2021 2:41:30 PM com.mquinn.trainer.ResultLoggerService log
INFO: 

mar 24, 2021 2:41:31 PM com.mquinn.trainer.ResultLoggerService log
INFO: Actual SVM Training Time: 00:00:00.834

mar 24, 2021 2:41:31 PM com.mquinn.trainer.ResultLoggerService log
INFO: Actual PCA Time: 00:00:00.0

mar 24, 2021 2:41:31 PM com.mquinn.trainer.ResultLoggerService log
INFO: 
**Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) C:\build\3_4_winpack-bindings-win64-vc14-static\opencv\modules\ml\src\svm.cpp:2118: error: (-212:Parsing error) SVM model data is invalid, check sv_count, var_* and class_count tags in function 'cv::ml::SVMImpl::write'
]
	at org.opencv.core.Algorithm.save_0(Native Method)
	at org.opencv.core.Algorithm.save(Algorithm.java:78)
	at com.mquinn.trainer.sl_extensions.SvmService.finaliseSVMTraining(SvmService.java:100)
	at com.mquinn.trainer.ImageProcessor.finalise(ImageProcessor.java:55)
	at com.mquinn.trainer.ImageRunner.getFilesDeep(ImageRunner.java:57)
	at com.mquinn.trainer.Main.main(Main.java:97)**

Process finished with exit code 1

I got only 1 dataset for testing, and the code lines af the exception are:

Algorithm.java:78: save_0(nativeObj, filename);
SvmService.java:100:  svm.save(runCounter + "_" + TRAINED_PATH);
ImageProcessor.java:55: svmService.finaliseSVMTraining(trainingData, true);
ImageRunner.java:57: processor.finalise();
Main.java:97: trainingRunner.getFilesDeep();

**Comment by Miki3553** [comment]
Now I try with 2 datasets and it still stops running when it finishes processing the first train folder :/ please help

**Comment by Mquinn960** [comment]
Hello there,

It sounds like the SVM trainer isn't getting the data it expects.

Have you followed the help repository for setting up your datasets in the correct folder structure?

When you debug the code, is it finding the desired images?

Matt

**Comment by Miki3553** [comment]
Hi again,
You're right, i don't set up my datasets in the correct folder structure
Now, I moved my images the way it says in the help repository and it works
To test, the program needs at least 2 classes in the dataset
Thanks
Greetings from Venezuela

**Comment by Mquinn960** [comment]
No worries :) Glad you got it working.

All the best,
Matt
