### ISSUE TITLE
ERROR while running on itellij

### ISSUE THREAD

**Issue by MemeGamer** [Mquinn960/offline-trainer#16]
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:

**Comment by Mquinn960** [comment]
Hello, 

Please try googling things like Maven errors before submitting issues to this repository.

https://stackoverflow.com/questions/43816009/how-to-fix-this-no-goals-have-been-specified-for-this-build-on-maven

In this case, I think you're missing a Maven argument:

`mvn package`
`mvn install`

etc.

Cheers,
Matt
