### ISSUE TITLE
Hello :)

### ISSUE THREAD

**Issue by JmKanmo** [Mquinn960/offline-trainer#7]
![Build](https://user-images.githubusercontent.com/48584943/55877628-8213ad00-5bd5-11e9-9045-e4ba20726dc3.PNG)
![error](https://user-images.githubusercontent.com/48584943/55877629-83dd7080-5bd5-11e9-9248-965b8f16eab0.PNG)
![error1](https://user-images.githubusercontent.com/48584943/55877631-863fca80-5bd5-11e9-8d23-0bf7a513a5aa.PNG)
![error2](https://user-images.githubusercontent.com/48584943/55877641-893abb00-5bd5-11e9-8ba9-cb01ca9e4018.PNG)

It's my errors :-(    

If you upload a guide,  please refer to my issue !

**Comment by Mquinn960** [comment]
@JmKanmo 

Hello mate,

I've added the OpenCV .jar files to the master and develop branches which will fix this issue for you. Please pull from develop and re-open your project.

P.S I will hopefully get some better instructions posted this weekend.

**Comment by JmKanmo** [comment]
Hello mate :)

I've been waiting for your some better instructions.

![error3](https://user-images.githubusercontent.com/48584943/56288088-f5c73400-6158-11e9-900b-503023e617f9.PNG)

If you have a time, could you help me fix this error ? :)

**Comment by Mquinn960** [comment]
Hello there,

Thank you for your patience, I will hopefully get some basic instructions written today (I have been very busy lately).

Did you see my comment above? could you try pulling the latest code from the ```develop``` branch again please and see if this solves your issue?

Kind regards,

Matt

**Comment by Mquinn960** [comment]
Hello @JmKanmo !

I have taken some time to write up a very thorough step-by-step guide for using these applications with some additional information about how they work, for your benefit, please see the repo README below;

https://github.com/Mquinn960/sign-language-help

I think this will illustrate an example workflow much better than the existing README overviews.

**Edit: in response to this actual query, please review the README for this project again as I have added Method 1 and Method 2 for running this app, either of which should solve your problem** 

Hope this helps!

Matt
